spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
  sql:
    init:
      mode: always # Ejecuta el schema.sql al arrancar
      logging:
        pattern:
          console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"